# fly.toml app configuration file generated for nebula-kingdoms on 2023-11-14T18:35:22+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nebula-kingdoms"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.status]
    port = 3000
    type = "http"
    interval = "30s"
    timeout = "60s"
    grace_period = "15s"
    method = "GET"
    path = "/misc/health"
    protocol = "http"
    tls_skip_verify = false
